

services:

  postgres:
    image: postgres:18
    container_name: marketplace-postgres

    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7

    container_name: marketplace-redis

    ports:
      - "6379:6379"

  chromadb:
    image: chromadb/chroma

    container_name: marketplace-chroma

    ports:
      - "8001:8000"

volumes:
  postgres_data: